version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env

    environment:
      NEXT_PUBLIC_APP_NAME: ${NEXT_PUBLIC_APP_NAME}
      OFFICE_LATITUDE: ${OFFICE_LATITUDE}
      OFFICE_LONGITUDE: ${OFFICE_LONGITUDE}
      OFFICE_RADIUS_METERS: ${OFFICE_RADIUS_METERS}

      DATABASE_URL: ${DATABASE_URL}
      NEXTAUTH_SECRET: ${AUTH_SECRET}
      ATTEDANCE_QRCODE_KEY: ${ATTEDANCE_QRCODE_KEY}
      TZ: ${TZ:-Asia/Makassar}
      NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost:3000}

    restart: unless-stopped